// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eahkjfoeqmhtwwbiuokz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhaGtqZm9lcW1odHd3Yml1b2t6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MjQ3MjMsImV4cCI6MjA2NDAwMDcyM30.gEDF4V6kvA-6xfHfz7cDFh2SxMqWhYn8FqYgmGnAiug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);